// Endpoint สำหรับดึงรายการเมนู
const API_URL = "https://script.google.com/macros/s/AKfycbxd_rlpa9t-V_V4PlmnU8sXOZJRDyUYYtrpn3y8GScDAF2aXptHN0CQfLJBr3bK2s7m/exec";

// รายการลิงก์เริ่มต้น (Fallback ในกรณีที่ API ดึงข้อมูลไม่สำเร็จหรือออฟไลน์)
const DEFAULT_PORTAL_LINKS = [
    { category: "บริการหลัก & ทั่วไป", title: "วันนี้", url: "https://script.google.com/macros/s/AKfycbx_c3eSGnwlczz90ye8pp9rR4cQawelLEZaZyqTvFiMao4ypZmL-5JZuGKVlZE0nI9djA/exec", icon: "ph-timer" },
    { category: "บริการหลัก & ทั่วไป", title: "PostIT TO-DO", url: "https://script.google.com/macros/s/AKfycbxoEOCVmg86PY_kP-dn4K3mrQUdBxcXPwVpTktKcYs_qhv_6NQjVfhbV-4UaF-l9L0noA/exec", icon: "ph-note-blank" },
    { category: "บริการหลัก & ทั่วไป", title: "ต้นกล้าอยากบอก", url: "https://script.google.com/macros/s/AKfycbwhCeZlgkOzHLgVnmBke8l_9XQvRNCjJy1NlkBoN1XeG716qaSqHQKzk-bucuugBXJcvg/exec", icon: "ph-chat-teardrop-text" },
    { category: "บริการหลัก & ทั่วไป", title: "ข้อความวิ่ง", url: "https://script.google.com/macros/s/AKfycbxmsu2UjG3a9Lxp23RbFbXUU09T7hfiE0jfHWe9LyNQQF3vhYJT9onkzkyH_M4q7yNrtg/exec", icon: "ph-chalkboard-simple" },
    { category: "ปฏิทินนัดหมาย & การจอง", title: "ปฏิทินนัดหมาย_ผอ.สยข.", url: "https://script.google.com/macros/s/AKfycbxteQXr79izbMSfBfwH7uX6fnX7N1eBz2qGlSs9hClipvuF_kF7vZ1w5pXLSTWt4kPsGw/exec", icon: "ph-calendar-check" },
    { category: "ปฏิทินนัดหมาย & การจอง", title: "ปฏิทินนัดหมาย_ผอ.สรก.", url: "https://script.google.com/macros/s/AKfycbzuSE2zgx7o0kFsp_fZrrFKtk7k3lkJGB5Goq8C9Spd5wwKbKiHlKTH4LiIhdseyWedKw/exec", icon: "ph-calendar-check" },
    { category: "ปฏิทินนัดหมาย & การจอง", title: "ปฏิทินนัดหมาย_ผอ.สบข.", url: "https://script.google.com/macros/s/AKfycbwrmXfrL2J9QORv0B4THEcgZ5TfG9Mrmy8qQtH4YL-4E5HO0z7vyFucpUX6XYIkeGa_/exec", icon: "ph-calendar-check" },
    { category: "ปฏิทินนัดหมาย & การจอง", title: "ปฏิทินนัดหมาย_รผอ.สสล.(2)", url: "https://script.google.com/macros/s/AKfycbyC4xCI34_VXDYenSFIUszfRF0B_RF4NaalG_t9x3OdkyLd8A-6rhkDRT-1F1wjJ5iB/exec", icon: "ph-calendar-check" },
    { category: "ปฏิทินนัดหมาย & การจอง", title: "ปฏิทินจองใช้สวน", url: "https://script.google.com/macros/s/AKfycbyZTnVLgshef_FDDfKH9Xb4ufE7SPwtOk3aafRgBY-fONc11BjWCGgIBGpjpOHz2c2O/exec", fallbackUrl: "https://script.google.com/macros/s/AKfycbyZTnVLgshef_FDDfKH9Xb4ufE7SPwtOk3aafRgBY-fONc11BjWCGgIBGpjpOHz2c2O/exec", icon: "ph-calendar-dots" },
    { category: "ปฏิทินนัดหมาย & การจอง", title: "Smart Parks Booking", url: "https://script.google.com/macros/s/AKfycby0Nwu1W6jNmVPqjhjaenEk8NYDJap1cZeMrP2otCi534RIE5W2aI5R4sJpgPmSdAKq3A/exec", icon: "ph-notebook" },
    { category: "ปฏิทินนัดหมาย & การจอง", title: "ปฎิทินชมดอกไม้", url: "https://script.google.com/macros/s/AKfycbzPNkp3O360z5Zg9yoBgk4JVWb4dmJ_-AcIZGn2iHfxJHkYodbbA6lG4Fi239SGzLjn6g/exec", icon: "ph-flower" },
    { category: "สวนสาธารณะ & พันธุ์ไม้", title: "สวนสาธารณะหลัก และสวน 15 นาที", url: "https://greenastrategy-hash.github.io/parkslocation/", icon: "ph-navigation-arrow" },
    { category: "สวนสาธารณะ & พันธุ์ไม้", title: "ธนาคารกล้าไม้", url: "https://script.google.com/macros/s/AKfycbyOMfgADOmQ_ybdQCir_EKwEcT_mko_w9KNVuMUjHaUu3Z9jrejT6c1tOM1xrA9ycpQiw/exec", icon: "ph-plant" },
    { category: "สวนสาธารณะ & พันธุ์ไม้", title: "บันทึกการบริหารจัดการการเพาะพันธุ์ไม้", url: "https://script.google.com/macros/s/AKfycbz44KIdFz0oraOU9vpGfon4WIj0rLn2608uHwRUlKtFQgBrGJsez9nb5PwAWojG9FOgag/exec", icon: "ph-leaf" },
    { category: "สวนสาธารณะ & พันธุ์ไม้", title: "บันทึกการขอความอนุเคราะห์ ประดับ ตกแต่ง สถานที่", url: "https://script.google.com/macros/s/AKfycbyVG9wHEHc_z6dtOlTLvWr1GWWbbmzLf4d6PnF6MvIZ0GpQoZv-C4bsia9VDh092qYEIQ/exec", icon: "ph-potted-plant" },
    { category: "แจ้งเหตุ ซ่อมบำรุง & ความปลอดภัย", title: "ระบบแจ้งสิงอำนวยความสะดวกชำรุด", url: "https://greenastrategy-hash.github.io/parksmanagement/", icon: "ph-warning-diamond" },
    { category: "แจ้งเหตุ ซ่อมบำรุง & ความปลอดภัย", title: "ระบบเก็บพิกัดและข้อมูล", url: "https://greenastrategy-hash.github.io/savelocation/", icon: "ph-lightbulb-filament" },
    { category: "แจ้งเหตุ ซ่อมบำรุง & ความปลอดภัย", title: "ระบบแจ้งไฟส่องสว่างชำรุด", url: "https://greenastrategy-hash.github.io/bmaalarmlight/", icon: "ph-lightbulb-filament" },
    { category: "แจ้งเหตุ ซ่อมบำรุง & ความปลอดภัย", title: "บันทึกการซ่อม/ติดตาม กลุ่มงานออกแบบ", url: "https://script.google.com/macros/s/AKfycbx3dcy6r7VWfapM6qVkDkmPbHnkJS7ED5dsCKyf4_Eyc5ZwCwz0ehi1WspZjwyKcS9C/exec", icon: "ph-wrench" },
    { category: "แจ้งเหตุ ซ่อมบำรุง & ความปลอดภัย", title: "บันทึกการซ่อม/ติดตาม ฝ่ายซ่อมบำรุง", url: "https://script.google.com/macros/s/AKfycbyImOyuX3Q3C_JBeZyRSsbUfzKYGNjYP1PkCXyyXi8skDH92XTYdC04SNiPgBASf8TELg/exec", icon: "ph-wrench" },
    { category: "แจ้งเหตุ ซ่อมบำรุง & ความปลอดภัย", title: "บันทึกการรายงานต้นไม้โค่นล้ม", url: "https://script.google.com/macros/s/AKfycbzh2L_mhfhv3THuWTQV6_IHQPEtAaiiy_KOlGo63l333_kFQ6vKmXNSrXjV-yBod3jXTw/exec", icon: "ph-tree" },
    { category: "แจ้งเหตุ ซ่อมบำรุง & ความปลอดภัย", title: "การรายงานผู้ประสบภาวะฉุกเฉินในสวนสาธารณะ", url: "https://script.google.com/macros/s/AKfycbxjwz9q0XWTkdzRQUK5vJcmRUuDmRI3GxD6-qS5OpRRUT5nxjOOCM3_1KujWqORBWjdoQ/exec", icon: "ph-ambulance" },
    { category: "แจ้งเหตุ ซ่อมบำรุง & ความปลอดภัย", title: "บันทึกการละเมิด", url: "https://script.google.com/macros/s/AKfycbw5DWcvksKVU55SLkKc1gNj4XcFRFWCtMAOEcqiskGEzkxbJDSAh_a-uZ8R0QjKzXZR/exec", icon: "ph-warning" },
    { category: "ติดตามงาน & คลังอุปกรณ์", title: "ระบบติดตามงาน ส่วนยุทธศาสตร์พื้นที่สีเขียว", url: "https://script.google.com/macros/s/AKfycbyd1ENUmVm-m_DkOerWjCWrmgVm2XH0likRt55ROosxiBXp7MByqXWm9cSkmZFF_u3h5w/exec", icon: "ph-brackets-square" },
    { category: "ติดตามงาน & คลังอุปกรณ์", title: "ระบบติดตามงาน", url: "https://script.google.com/macros/s/AKfycbyHzpvHFokGVP7JDno_hexMFADcMJitWPrHtk4Z1n6mReXHb_WoMAe0zG6XyLx3n1LXHw/exec", icon: "ph-brackets-square" },
    { category: "ติดตามงาน & คลังอุปกรณ์", title: "Timeline รายงานความคืบหน้า งานก่อสร้าง ปรับปรุง", url: "https://script.google.com/macros/s/AKfycbw_JZVQVDx-wGm1IrxwnnRqbsuLQ1wQUskL3kNMUrmbVPDJI2Egei5RmctkOLqlrFuSGw/exec", icon: "ph-hourglass-simple-medium" },
    { category: "ติดตามงาน & คลังอุปกรณ์", title: "บันทึกความคืบหน้า", url: "https://script.google.com/macros/s/AKfycbwnuTiUBOc0rO_CwqOAaX7sTbWAXwNGJlSGcx2UfGf7TNUk95m2QlunlNHLwo75TkdB/exec", icon: "ph-hourglass-simple-medium" },
    { category: "ติดตามงาน & คลังอุปกรณ์", title: "บันทึกความสะอาด", url: "https://script.google.com/macros/s/AKfycbw2LuR5Q1iGNej-ekXLYW1Ends9WAcXVidceJDAgUHn35XCTe7NFUzJRmegpgT12A1wRw/exec", icon: "ph-broom" },
    { category: "ติดตามงาน & คลังอุปกรณ์", title: "บันทึกวัสดุอุปกรณ์", url: "https://script.google.com/macros/s/AKfycbwVWzeOW8DDRet332eG9Mns1n9itb4t6CYVSTYTQWOGyOFODWnZdVEz3rUci5yqks2WGg/exec", icon: "ph-dresser" },
    { category: "ติดตามงาน & คลังอุปกรณ์", title: "บันทึกวัสดุอุปกรณ์ (กลุ่มงานออกแบบ)", url: "https://script.google.com/macros/s/AKfycbzfKa5FhwUMJ8xJhplneGUudyl7YqSbYsRWNOrSLlRpG_8jQmCI5zPYPWpdyszDAbyZ-Q/exec", icon: "ph-dresser" },
    { category: "สถิติ & สารสนเทศ", title: "สถิติการจองใช้สวน", url: "https://datastudio.google.com/embed/u/0/reporting/3ce1d2f3-c7ea-445b-8af2-38f803300c0a/page/KrHGE", icon: "ph-chart-line" },
    { category: "สถิติ & สารสนเทศ", title: "สถิติการเข้าชม Bangkok City Model", url: "https://datastudio.google.com/embed/reporting/06a7c542-2a0f-4394-984f-11f958c0dc02/page/hGp4D", icon: "ph-chart-line" },
    { category: "สถิติ & สารสนเทศ", title: "สถิติการเข้าชมอุทยานผีเสื้อและแมลงกรุงเทพฯ", url: "https://datastudio.google.com/embed/u/0/reporting/db477611-c715-494a-af4f-597175fdfde5/page/p_2xuv5tbbmd", icon: "ph-chart-donut" },
    { category: "สถิติ & สารสนเทศ", title: "สถิติการลอยกระทง", url: "https://datastudio.google.com/embed/reporting/f628149e-2c94-4b97-b639-05771cca18b4/page/BQLjD", icon: "ph-chart-donut" },
    { category: "สถิติ & สารสนเทศ", title: "สถิติสวนสำหรับสัตว์เลี้ยง", url: "https://script.google.com/macros/s/AKfycbyQ7XBI_sol2tLRtpC6VawJInxgmforyXbcwWhoijPCSvGq_tc1gDq9Hrz_puZEP1Mb/exec", icon: "ph-chart-bar" },
    { category: "องค์กร & เครื่องมือ", title: "ผังองค์กร", url: "https://script.google.com/macros/s/AKfycbxQOoW7HLRVaHsZicCu9tuhy5Di-I28vAzkKFFbDWfzbq2x8qlQfvQafbott1C4ztiS/exec", icon: "ph-network" },
    { category: "องค์กร & เครื่องมือ", title: "ผังหน่วยงาน", url: "https://script.google.com/macros/s/AKfycbwRY4W3fG2fJVevn_1roiCFnHWLshS2EeRKnuXujcMB29VdCuaFou-2_kcGNKi-qTQ5jA/exec", icon: "ph-users" },
    { category: "องค์กร & เครื่องมือ", title: "Tools Hub", url: "https://script.google.com/macros/s/AKfycbw8lIIlO4hs6dOUd-ePwnzp8AAGWi6w73e4VP9eWxc9gNkdBLAskHEmpjx63nhbtxZ3ag/exec", icon: "ph-toolbox" },
    { category: "องค์กร & เครื่องมือ", title: "PDF <> IMG", url: "https://script.google.com/macros/s/AKfycbzbUJHqXDBsGRK6-eYaPmUafFi1t7m66q0wx4Lxnbwxdq2r9sHUpa95VzO1zWnXaIb5Xg/exec", icon: "ph-file-pdf" },
    { category: "องค์กร & เครื่องมือ", title: "สภาพอากาศ", url: "https://script.google.com/macros/s/AKfycbyc53ciy6r8hq0SCEqhg7BmO8YeitiX3D6VhB5scKCEeiXPAyhnUKYJt2Vnm_FW8YpV/exec", icon: "ph-cloud-moon" }
];
